### ISSUE TITLE
Mass upload support

### ISSUE THREAD

**Issue by vranki** [conikuvat/edegal#182]
Currently there doesn't seem to be possibility to import lot of images. It should be possible to upload multiple files and/or upload a zip file containing photos.

Another way would be to upload the files to a selected directory on server. 

Something like this is really needed. If it is possible, please mention it in the documentation. Otherwise this looks like really promising gallery software.

**Comment by japsu** [comment]
Currently the following ways of uploading multiple pictures are supported:

1. In the Django admin (`https://yourgallery.example.com/admin/`), navigate to an album and select "MultiUpload". Drag multiple images to the browser window. Hit "Start upload".
2. Upload files to a server on the directory. Use the `python manage.py import_files` admin command.

Do these fulfil your use case? If not, please reopen with clarifications.

Please note the `import_files` has gone largely untested for the past year or so, so it may be broken. Please open an issue if so. Examples of `import_files` syntax:

```
# only works if the pictures are under MEDIA_ROOT
python manage.py import_files --mode inplace --path /url/path/to/parent/album /media/root/path/to/*.jpeg

# also work with files not under MEDIA_ROOT
python manage.py import_files --mode copy --path /url/path/to/parent/album /any/path/to/*.jpeg
python manage.py import_files --mode move --path /url/path/to/parent/album /any/path/to/*.jpeg
```

Related source files:
https://github.com/conikuvat/edegal/blob/master/backend/edegal/management/commands/import_files.py
https://github.com/conikuvat/edegal/blob/master/backend/edegal/importers/filesystem.py
https://github.com/conikuvat/edegal/blob/master/backend/edegal/models/media.py
